image: node:latest

stages:
  - lint
  - test

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint
  tags:
    - docker

test:
  stage: test
  variables:
    NODE_ENV: test
  script:
    - npm test
  tags:
    - docker
